export const GET_ALL_ARTICLES = "GET_ALL_ARTICLES";
export const GET_ARTICLES_BY_NAME = "GET_ARTICLES_BY_NAME";
export const GET_ARTICLES_BY_ID = 'GET_ARTICLES_BY_ID';
export const CREATE_ARTICLE = "CREATE_ARTICLE";