export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES';
export const GET_CATEGORY_ARTICLES = 'GET_CATEGORY_ARTICLES';
export const GET_CATEGORY_ARTICLES_BY_NAME = 'GET_CATEGORY_ARTICLES_BY_NAME';
export const FILTER_BY_PRICE = 'FILTER_BY_PRICE';
export const FILTER_BY_SIZE = 'FILTER_BY_SIZE';
export const ORDER_BY_PRICE = 'ORDER_BY_PRICE';
export const RESET_FILTERS = 'RESET_FILTERS';
export const UPDATE_FILTERED_PRODUCTS = 'UPDATE_FILTERED_PRODUCTS';